google_to_tesseract_lowercase = {
    "afrikaans": "afr",
    "albanian": "sqi",
    "amharic": "amh",
    "arabic": "ara",
    "armenian": "hye",
    "azerbaijani": "aze",
    "basque": "eus",
    "belarusian": "bel",
    "bengali": "ben",
    "bosnian": "bos",
    "bulgarian": "bul",
    "catalan": "cat",
    "cebuano": "ceb",
    "chichewa": "nya",
    "chinese (simplified)": "chi_sim",
    "chinese (traditional)": "chi_tra",
    "corsican": "cos",
    "croatian": "hrv",
    "czech": "ces",
    "danish": "dan",
    "dutch": "nld",
    "english": "eng",
    "esperanto": "epo",
    "estonian": "est",
    "filipino": "fil",
    "finnish": "fin",
    "french": "fra",
    "frisian": "fry",
    "galician": "glg",
    "georgian": "kat",
    "german": "deu",
    "greek": "ell",
    "gujarati": "guj",
    "haitian creole": "hat",
    "hausa": "hau",
    "hawaiian": "haw",
    "hebrew": "heb",
    "hindi": "hin",
    "hmong": "hmn",
    "hungarian": "hun",
    "icelandic": "isl",
    "igbo": "ibo",
    "indonesian": "ind",
    "irish": "gle",
    "italian": "ita",
    "japanese": "jpn",
    "javanese": "jav",
    "kannada": "kan",
    "kazakh": "kaz",
    "khmer": "khm",
    "korean": "kor",
    "kurdish (kurmanji)": "kur",
    "kyrgyz": "kir",
    "lao": "lao",
    "latin": "lat",
    "latvian": "lav",
    "lithuanian": "lit",
    "luxembourgish": "ltz",
    "macedonian": "mkd",
    "malagasy": "mlg",
    "malay": "msa",
    "malayalam": "mal",
    "maltese": "mlt",
    "maori": "mri",
    "marathi": "mar",
    "mongolian": "mon",
    "myanmar (burmese)": "mya",
    "nepali": "nep",
    "norwegian": "nor",
    "odia": "ori",
    "pashto": "pus",
    "persian": "fas",
    "polish": "pol",
    "portuguese": "por",
    "punjabi": "pan",
    "romanian": "ron",
    "russian": "rus",
    "samoan": "smo",
    "scots gaelic": "gla",
    "serbian": "srp",
    "sesotho": "sot",
    "shona": "sna",
    "sindhi": "snd",
    "sinhala": "sin",
    "slovak": "slk",
    "slovenian": "slv",
    "somali": "som",
    "spanish": "spa",
    "sundanese": "sun",
    "swahili": "swa",
    "swedish": "swe",
    "tagalog": "tgl",
    "tajik": "tgk",
    "tamil": "tam",
    "telugu": "tel",
    "thai": "tha",
    "turkish": "tur",
    "ukrainian": "ukr",
    "urdu": "urd",
    "uyghur": "uig",
    "uzbek": "uzb",
    "vietnamese": "vie",
    "welsh": "cym",
    "xhosa": "xho",
    "yiddish": "yid",
    "yoruba": "yor",
    "zulu": "zul"
}

def get_tesseract_code(lang):
    return google_to_tesseract_lowercase.get(lang.lower(),None)


